/// Flutter icons CustomIcon
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcon
///      fonts:
///       - asset: fonts/CustomIcon.ttf
///
/// 
/// * Iconic, Copyright (C) 2012 by P.J. Onori
///         Author:    P.J. Onori
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://somerandomdude.com/work/iconic/
///
import 'package:flutter/widgets.dart';

class CustomIcon {
  CustomIcon._();

  static const _kFontFam = 'CustomIcon';
  static const String? _kFontPkg = null;

  static const IconData search = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mail = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart_empty = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData star = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData video = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData picture = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ok_circle = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel_circle = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plus_circle = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData minus_circle = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData info = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData link = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData attach = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_empty = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_open = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock_open_empty = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pin = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tag_empty = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download_cloud = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData upload_cloud = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quote_left = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quote_right = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quote_left_alt = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData quote_right_alt = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil_neg = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pencil_alt = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData undo = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_inv = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_alt = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_inv_alt = IconData(0xe82d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_alt2 = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment_inv_alt2 = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe830, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_inv = IconData(0xe831, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location = IconData(0xe832, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_inv = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData location_alt = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData compass = IconData(0xe835, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash = IconData(0xe836, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trash_empty = IconData(0xe837, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc_inv = IconData(0xe839, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc_alt = IconData(0xe83a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData doc_inv_alt = IconData(0xe83b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData article = IconData(0xe83c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData article_alt = IconData(0xe83d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_open = IconData(0xe83e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder = IconData(0xe83f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData folder_empty = IconData(0xe840, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData box = IconData(0xe841, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rss = IconData(0xe842, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rss_alt = IconData(0xe843, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cog = IconData(0xe844, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wrench = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe846, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe847, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_inv = IconData(0xe848, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar_alt = IconData(0xe849, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mic = IconData(0xe84a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_off = IconData(0xe84b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData volume_up = IconData(0xe84c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData headphones = IconData(0xe84d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe84e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lamp = IconData(0xe84f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData block = IconData(0xe850, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_full = IconData(0xe851, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_full_alt = IconData(0xe852, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_small = IconData(0xe853, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_small_alt = IconData(0xe854, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_vertical = IconData(0xe855, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData resize_horizontal = IconData(0xe856, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData move = IconData(0xe857, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData popup = IconData(0xe858, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down = IconData(0xe859, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left = IconData(0xe85a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right = IconData(0xe85b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up = IconData(0xe85c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down_circle = IconData(0xe85d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left_circle = IconData(0xe85e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right_circle = IconData(0xe85f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up_circle = IconData(0xe860, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cw = IconData(0xe861, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loop = IconData(0xe862, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData loop_alt = IconData(0xe863, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData exchange = IconData(0xe864, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData split = IconData(0xe865, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData arrow_curved = IconData(0xe866, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play = IconData(0xe867, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData play_circle2 = IconData(0xe868, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData stop = IconData(0xe869, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pause = IconData(0xe86a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData to_start = IconData(0xe86b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData to_end = IconData(0xe86c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eject = IconData(0xe86d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData target = IconData(0xe86e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData signal = IconData(0xe86f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData award = IconData(0xe870, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData award_empty = IconData(0xe871, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list = IconData(0xe872, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData list_nested = IconData(0xe873, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bat_empty = IconData(0xe874, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bat_half = IconData(0xe875, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bat_full = IconData(0xe876, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bat_charge = IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mobile = IconData(0xe878, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cd = IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData equalizer = IconData(0xe87a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cursor = IconData(0xe87b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData aperture = IconData(0xe87c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData aperture_alt = IconData(0xe87d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData steering_wheel = IconData(0xe87e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book = IconData(0xe87f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book_alt = IconData(0xe880, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brush = IconData(0xe881, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brush_alt = IconData(0xe882, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eyedropper = IconData(0xe883, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layers = IconData(0xe884, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData layers_alt = IconData(0xe885, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun = IconData(0xe886, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sun_inv = IconData(0xe887, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud = IconData(0xe888, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rain = IconData(0xe889, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flash = IconData(0xe88a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon = IconData(0xe88b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon_inv = IconData(0xe88c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData umbrella = IconData(0xe88d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_bar = IconData(0xe88e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_pie = IconData(0xe88f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chart_pie_alt = IconData(0xe890, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key = IconData(0xe891, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData key_inv = IconData(0xe892, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hash = IconData(0xe893, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData at = IconData(0xe894, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pilcrow = IconData(0xe895, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dial = IconData(0xe896, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData facebook_round_color_icon = IconData(0xe897, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kakaotalk_icon = IconData(0xe898, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_social_media_logo_icon = IconData(0xe899, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
